"""Generate HTML and markdown reports from simulation results."""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns


def _medal(rank: int) -> str:
    return {1: "🥇", 2: "🥈", 3: "🥉"}.get(rank, "")


def build_odds_table(sim_results: dict[str, dict]) -> pd.DataFrame:
    rows = []
    for team, data in sim_results.items():
        if team.startswith("_"):
            continue
        rows.append({
            "Team": team,
            "Champion %": f"{data.get('champion', 0)*100:.1f}",
            "Final %": f"{data.get('final', 0)*100:.1f}",
            "Semifinal %": f"{data.get('semifinal', 0)*100:.1f}",
            "Quarterfinal %": f"{data.get('quarterfinal', 0)*100:.1f}",
            "R16 %": f"{data.get('r16', 0)*100:.1f}",
            "Qualified %": f"{data.get('group_qualified', 0)*100:.1f}",
            "Avg Pts": f"{data.get('avg_group_points', 0):.2f}",
        })
    df = pd.DataFrame(rows)
    df["_champ_num"] = df["Champion %"].astype(float)
    df = df.sort_values("_champ_num", ascending=False).drop(columns="_champ_num")
    df.index = range(1, len(df) + 1)
    return df


def champion_bar_chart(sim_results: dict[str, dict], out_path: Path, top_n: int = 20) -> None:
    rows = [(t, d.get("champion", 0) * 100) for t, d in sim_results.items() if not t.startswith("_")]
    rows.sort(key=lambda x: x[1], reverse=True)
    rows = rows[:top_n]
    teams, probs = zip(*rows)

    fig, ax = plt.subplots(figsize=(12, 6))
    bars = ax.barh(list(reversed(teams)), list(reversed(probs)), color=sns.color_palette("viridis", top_n))
    ax.set_xlabel("Championship probability (%)")
    ax.set_title("FIFA World Cup 2026 - Predicted Championship Odds")
    for bar, prob in zip(bars, reversed(probs)):
        ax.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height() / 2,
                f"{prob:.1f}%", va="center", fontsize=9)
    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=150)
    plt.close()


def render_html(
    sim_results: dict[str, dict],
    metrics: dict | None,
    out_path: Path,
) -> None:
    """Generate a self-contained HTML report."""
    odds_df = build_odds_table(sim_results)
    meta = sim_results.get("_meta", {})
    n_runs = meta.get("n_runs", "?")
    top_finals = meta.get("top_final_pairings", [])

    chart_path = out_path.parent / "champion_odds.png"
    champion_bar_chart(sim_results, chart_path)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>FIFA World Cup 2026 Predictions</title>
<style>
  body {{ font-family: Arial, sans-serif; max-width: 1200px; margin: auto; padding: 20px; }}
  h1 {{ color: #1a1a2e; }}
  h2 {{ color: #16213e; border-bottom: 2px solid #e94560; padding-bottom: 6px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
  th {{ background: #1a1a2e; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #ddd; }}
  tr:nth-child(even) {{ background: #f5f5f5; }}
  tr:hover {{ background: #e8f4fd; }}
  .champion {{ background: #fff3cd !important; font-weight: bold; }}
  img {{ max-width: 100%; margin: 20px 0; }}
  .metric {{ display: inline-block; margin: 10px; padding: 10px 20px;
             background: #e8f4fd; border-radius: 8px; }}
</style>
</head>
<body>
<h1>⚽ FIFA World Cup 2026 Predictions</h1>
<p>Based on <strong>{n_runs:,} Monte Carlo simulations</strong> using historical match data,
Elo ratings, player squad strength, venue conditions, and climate features.</p>

<h2>Championship Odds</h2>
<img src="champion_odds.png" alt="Championship odds chart">

<h2>Full Tournament Probability Table</h2>
{odds_df.to_html(index=True, border=0, classes="odds-table")}

<h2>Most Likely Finals</h2>
<table>
<tr><th>Rank</th><th>Matchup</th><th>Probability</th></tr>
"""
    for i, (teams, prob) in enumerate(top_finals[:10], 1):
        t1, t2 = teams[0], teams[1] if len(teams) > 1 else ("?", "?")
        html += f"<tr><td>{i}</td><td>{t1} vs {t2}</td><td>{prob*100:.2f}%</td></tr>\n"
    html += "</table>\n"

    if metrics:
        html += "<h2>Model Performance</h2>\n"
        for k, v in metrics.items():
            if isinstance(v, float):
                html += f'<div class="metric"><strong>{k}</strong>: {v:.4f}</div>\n'

    html += """
<footer style="margin-top:40px; color:#888; font-size:0.85em;">
  Generated by the WM FIFA 2026 prediction system.
</footer>
</body>
</html>"""

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(html)

    print(f"Report saved to {out_path}")
